### ISSUE TITLE
Use bcrypt instead of SHA-1

### ISSUE THREAD

**Issue by kubp** [totaljs/messenger#1]
You should store passwords using some modern hash algorithms like bcrypt.

**Comment by petersirka** [comment]
@kubp yes, but I think that for personal usage is SHA1 OK. You can change hash algorithm to e.g. `sha256`, `sha512` (with salt) or something else in:

```javascript
// models/login.js:8
if (user && user.password == model.password.sha512('salt')) {}

// models/users.js:38 and 44
model.password && !model.password.startsWith('****') && (tmp.password = model.password.sha512('salt'));
tmp.password = model.password.sha512('salt');
```
Thank you!

**Comment by kubp** [comment]
I didn't know that, thank you for examples. But I would still set at least sha512 as the default option.
