### ISSUE TITLE
 (SQL/NoSQL) database integration

### ISSUE THREAD

**Issue by despider001** [totaljs/messenger#3]
First of all congratulation for such a job. As far as I understood, data is stored under database directory.  I wonder how to integrate remote database (SQL or NoSQL) to this project.

**Comment by petersirka** [comment]
Hi @despider001,
thank you very much. Yes, you can integrate remote database but you need to rewrite code with DB implementation manually. You can't switch DB easily, but it's not hard.

**Comment by despider001** [comment]
Thank you for you quick reply. Since I'm not familiar with totaljs, I'm having a little tough time to understand which part is responsible for what. Your code is very neat and clean, yet does not have comments. A huge thumbs up for your efforts though. I would humbly ask you to make some sort of documentation so that it becomes easier for newbie developers like us to be helped from your code base.

**Comment by petersirka** [comment]
Yes, first you need to learn Total.js / jComponent and then you'll understand each Total.js product. Nothing goes fast and you need time to undertand (but a lot of developers don't have time for learning -- and this is the big problem). 

- [__Total.js documentation__](https://docs.totaljs.com/latest/en.html#pages~Getting%20started)
- [__Wiki__ with missing Messenger](https://wiki.totaljs.com/)

---

I wish a better documentation too, but I'm alone for everything so it takes ...

**Comment by despider001** [comment]
thank you sir. I'll try to learn Total.js
keep up good work :)
