### ISSUE TITLE
Custom PFPs dont save

### ISSUE THREAD

**Issue by ghost** [totaljs/messenger#6]
When I set up a new PFP it doesn't save into a database and it shows as a broken image icon. Please help!

I deployed the application into a web server, so all the data should be on that server, and not the computer.

**Comment by petersirka** [comment]
HI @BKenzie7 , sorry for delay.

What does mean `PFP`?

**Comment by ghost** [comment]
The PFP is the Profile Photos, or the Avatars, the picture next to the
user's name.

**Comment by petersirka** [comment]
Understand and good to know. Please look into the application log what it contains. I'm very curious.
