### ISSUE TITLE
https://messanger.mydomain.com fails to load through ssl connection

### ISSUE THREAD

**Issue by duralitt** [totaljs/messenger#7]
i have setup the messenger in SuperAdmin to work with ssl. unfortunately the login page does not load as it does in http correctly . do I miss some configuration at this point it seems that the framework is not loaded correctly through ssl.

![image](https://user-images.githubusercontent.com/58336046/70782927-755cdf80-1d88-11ea-82a3-fe58c72db351.png)

![image](https://user-images.githubusercontent.com/58336046/70782966-8efe2700-1d88-11ea-8ee7-69330095d109.png)

**Comment by petersirka** [comment]
Hi. I have tested it and everything works correctly. The log contains a bug with jComponent library, it doens't loaded and I don't know why.

**Comment by petersirka** [comment]
Did you download it from SuperAdmin directly?

**Comment by duralitt** [comment]
Hi, yes I load through SuperAdmin as the main application

**Comment by duralitt** [comment]
hmm ok  , i also setup the CMS to work through SSL and it works without any problems
i am just struggling with the messenger

**Comment by duralitt** [comment]
how do you setup the messenger in SuperAdmin on the same server with SSL and SuperAdmin itself also running in ssl ? maybe it is an Nginx config problem ? how does your configuration look like or do you always have different server for SuperAdmin and one extra for the messenger ?

**Comment by duralitt** [comment]
stupid me, sorry it works now perfectly after clearing browser cache
